/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_psi_bitshuffle_BitShuffleLZ4JNI */

#ifndef _Included_ch_psi_bitshuffle_BitShuffleLZ4JNI
#define _Included_ch_psi_bitshuffle_BitShuffleLZ4JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_psi_bitshuffle_BitShuffleLZ4JNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_psi_bitshuffle_BitShuffleLZ4JNI_init
  (JNIEnv *, jclass);

/*
 * Class:     ch_psi_bitshuffle_BitShuffleLZ4JNI
 * Method:    Bitshuffle_bitshuffle
 * Signature: ([BLjava/nio/ByteBuffer;I[BLjava/nio/ByteBuffer;IIII)I
 */
JNIEXPORT jint JNICALL Java_ch_psi_bitshuffle_BitShuffleLZ4JNI_Bitshuffle_1bitshuffle
  (JNIEnv *, jclass, jbyteArray, jobject, jint, jbyteArray, jobject, jint, jint, jint, jint);

/*
 * Class:     ch_psi_bitshuffle_BitShuffleLZ4JNI
 * Method:    Bitshuffle_bitunshuffle
 * Signature: ([BLjava/nio/ByteBuffer;I[BLjava/nio/ByteBuffer;IIII)I
 */
JNIEXPORT jint JNICALL Java_ch_psi_bitshuffle_BitShuffleLZ4JNI_Bitshuffle_1bitunshuffle
  (JNIEnv *, jclass, jbyteArray, jobject, jint, jbyteArray, jobject, jint, jint, jint, jint);

/*
 * Class:     ch_psi_bitshuffle_BitShuffleLZ4JNI
 * Method:    Bitshuffle_LZ4_compress
 * Signature: ([BLjava/nio/ByteBuffer;I[BLjava/nio/ByteBuffer;IIII)I
 */
JNIEXPORT jint JNICALL Java_ch_psi_bitshuffle_BitShuffleLZ4JNI_Bitshuffle_1LZ4_1compress
  (JNIEnv *, jclass, jbyteArray, jobject, jint, jbyteArray, jobject, jint, jint, jint, jint);

/*
 * Class:     ch_psi_bitshuffle_BitShuffleLZ4JNI
 * Method:    Bitshuffle_LZ4_decompress
 * Signature: ([BLjava/nio/ByteBuffer;I[BLjava/nio/ByteBuffer;IIII)I
 */
JNIEXPORT jint JNICALL Java_ch_psi_bitshuffle_BitShuffleLZ4JNI_Bitshuffle_1LZ4_1decompress
  (JNIEnv *, jclass, jbyteArray, jobject, jint, jbyteArray, jobject, jint, jint, jint, jint);

/*
 * Class:     ch_psi_bitshuffle_BitShuffleLZ4JNI
 * Method:    Bitshuffle_LZ4_bound
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_ch_psi_bitshuffle_BitShuffleLZ4JNI_Bitshuffle_1LZ4_1bound
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     ch_psi_bitshuffle_BitShuffleLZ4JNI
 * Method:    Bitshuffle_default_block_size
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ch_psi_bitshuffle_BitShuffleLZ4JNI_Bitshuffle_1default_1block_1size
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
